GuiSize() {
	global
	Anchor(GB_EditHS, "wh", 1)
	Anchor(GB_Trigger, "w", 1)
	Anchor(TriggerID, "w")
	Anchor(GB_Options, "x", 1)
	Anchor(OptionsID, "x")	
	Anchor(OptionsListID, "x", 1)
	Anchor(HelpTxtID, "x")
	Anchor(GB_Replacement, "wh", 1)
	Anchor(ReplacementID, "wh")
	Anchor("BT_Add", "y", 1)
	Anchor("BT_Clear", "y", 1)
	Anchor("BT_Repl", "y", 1)
	Anchor("BT_Find", "y", 1)
	Anchor("BtnEdit", "y", 1)
	Anchor("BtnDelete", "y", 1)
	Anchor(Btn_EditAHK, "xy", 1)
	Anchor(GB_Hotstrings, "wy", 1)
	Anchor(HSListID, "wy", 1)
	Anchor(VersionTxt, "y")
	Anchor(saveButton, "yx.5", 1)
	Anchor(CloseButton, "yx.5", 1)
	return
}